-- Fix doctor designations from labaid_doctors.json

UPDATE public.legacy_doctors SET designation = 'Chief Cardiac Surgeon' WHERE name = 'Dr. Lutfor Rahman';
UPDATE public.legacy_doctors SET designation = 'Senior Consultant Cardiologist  Director, Cardiac Cath Lab & Heart Rhythm Services   Professor, School of Health Science' WHERE name = 'Dr. A P M Sohrabuzzaman';
UPDATE public.legacy_doctors SET designation = 'Senior Fellowship in Cardiology (Singapore), Senior Consultant Cardiologist,  Chief Medical Education and Research' WHERE name = 'Professor Dr. Baren Chakraborty';
UPDATE public.legacy_doctors SET designation = 'Senior Consultant Cardiologist & Medicine Specialist In-Charge: Coronary Care Unit (CCU)' WHERE name = 'Dr. Mahbubor Rahman';
UPDATE public.legacy_doctors SET designation = 'General & Laparoscopic Surgeon  Ex. Professor and Head, Department of Surgery' WHERE name = 'Professor Dr. M Khademul Islam';
UPDATE public.legacy_doctors SET designation = 'Ex. Professor & Head, Department of Orthopedic Surgery Chief Consultant & Head, Department of Orthopedic Surgery' WHERE name = 'Professor Dr. M. Amjad Hossain';
UPDATE public.legacy_doctors SET designation = 'Urologist, Andrologist & Uro-Oncologist  Chief Consultant & Head of the Dept. of Urology' WHERE name = 'Professor. Dr. Md. Jahangir Kabir';
UPDATE public.legacy_doctors SET designation = 'Gynecologist, Obstetrician & Infertility Specialist  Sr. Consultant' WHERE name = 'Professor (Dr.) Mariam Faruqui (Shati)';
UPDATE public.legacy_doctors SET designation = 'Medicine & Chest specialist Professor, Medicine' WHERE name = 'Professor. (Dr.) F. M. Siddiqui';
UPDATE public.legacy_doctors SET designation = 'Medicine Specialist & Pulmonologist' WHERE name = 'Professor Dr. Ali Hossain';
UPDATE public.legacy_doctors SET designation = 'Specialist in Internal Medicine & Kidney Disease  Professor, Dept. of Nephrology' WHERE name = 'Professor. Dr. Muhammad Rafiqul Alam';
UPDATE public.legacy_doctors SET designation = 'Professor of Hepatology (Former) UGC Professor & Course Director, Medical Faculty (Former)' WHERE name = 'Professor Dr. Salimur Rahman';
UPDATE public.legacy_doctors SET designation = 'Newborn & Child Specialist Ex. Chairman' WHERE name = 'Professor Dr. Md. Abdul Mannan';
UPDATE public.legacy_doctors SET designation = 'Senior Consultant, Labaid Specialized Hospital' WHERE name = 'Prof. Sehereen F. Siddiqua';
UPDATE public.legacy_doctors SET designation = 'Kidney Diseases & Medicine Specialist Associate Professor & Head of the Dept. (Ex.), Nephrology,Consultant' WHERE name = 'Dr. Mohammad Moniruzzaman';
UPDATE public.legacy_doctors SET designation = 'Professor of Cardiology,  Clinical and Interventional Cardiologist,  Ex. Professor of Cardiology National Institute of Cardiovascular Diseases, Senior Consultant' WHERE name = 'Professor Dr. Abduz Zaher';
UPDATE public.legacy_doctors SET designation = 'General, Laparoscopic, Colorectal & Cancer Specialist Surgeon , Professor' WHERE name = 'Prof. Dr. Md. Saifullah';
UPDATE public.legacy_doctors SET designation = 'Arthroscopy & Replacement Surgeon  Ex. Chairman & Head of Department, Orthopaedic Surgery' WHERE name = 'Professor. Dr. Abu Zaffar Chowdhury (Biru)';
UPDATE public.legacy_doctors SET designation = 'Medicine, Asthma & Chest Diseases Specialist Ex. Consultant,Assoc. Professor' WHERE name = 'Professor Dr. Md. Sayedul Islam';
UPDATE public.legacy_doctors SET designation = 'Specialist in Neurology & Internal Medicine, Chief Consultant' WHERE name = 'Professor Dr. Sirajul Haque';
UPDATE public.legacy_doctors SET designation = 'Cardiac Surgeon, Senior Consultant' WHERE name = 'Dr. Md. Lokman Hossain';
UPDATE public.legacy_doctors SET designation = 'Professor, Gastroenterology Department  Specialist in Gastrointestinal & Liver Diseases' WHERE name = 'Professor (Dr.) Mian Mashhud Ahmad';
UPDATE public.legacy_doctors SET designation = 'Advanced Laparoscopic Colorectal Surgeon Chairman, Department of Colorectal Surgery' WHERE name = 'Professor. Dr. Shahadot Hossain Sheikh';
UPDATE public.legacy_doctors SET designation = 'Ex. Professor,  Specialist in Medicine & Neurology, Senior Consultant' WHERE name = 'Professor Dr. Md. Ashraf Ali';
UPDATE public.legacy_doctors SET designation = 'Medicine Specialist, Senior Consultant' WHERE name = 'Professor. Dr. Samiran Kumar Saha';
UPDATE public.legacy_doctors SET designation = 'Medicine Specialist & Cardiologist Senior Consultant' WHERE name = 'Dr. Nur Mohammad';
UPDATE public.legacy_doctors SET designation = 'Professor, Department of Neurosurgery' WHERE name = 'Professor. Dr. Moududul Haque';
UPDATE public.legacy_doctors SET designation = 'Clinical & Interventional Cardiologist Senior Consultant & In charge (CCU-2)' WHERE name = 'Dr. Arun Kumar Sharma';
UPDATE public.legacy_doctors SET designation = 'Kidney Disease & Medicine Specialist, Associate Professor, AMCH Ex. , Consultant' WHERE name = 'Dr. A.S.M. Julfekar Helal';
UPDATE public.legacy_doctors SET designation = 'Fellow in Diagnostic and Interventional Paediatric Cardiology & Intensive Care, PSCC, KSA Pediatric Interventional Cardiologist' WHERE name = 'Brig. Gen. Professor Nurunnahar Fatema S.B.P';
UPDATE public.legacy_doctors SET designation = 'Neuro Medicine & Stroke Interventional Neurology Specialist, Professor & Head of Dept. of Interventional Neurology' WHERE name = 'Professor Dr. Kazi Mohibur Rahman';
UPDATE public.legacy_doctors SET designation = 'Neuro Surgeon & Spine Surgeon, Associate Professor, Department of Neurosurgery' WHERE name = 'Dr. S.I.M. Khairun Nabi Khan';
UPDATE public.legacy_doctors SET designation = 'Specialist in Medicine, Gastro-intestinal & Liver Diseases Ex. Professor & Head, Dept. of Gastroenterology' WHERE name = 'Professor. Dr. Bimal Chandra Shil';
UPDATE public.legacy_doctors SET designation = 'Oncologist' WHERE name = 'Dr. A.F.M. Kamal Uddin';
UPDATE public.legacy_doctors SET designation = 'Urology Specialist  Professor, Department of Urology  Bangladesh Medical University (BMU) (Ex. PG Hospital), Dhaka.' WHERE name = 'Prof. Dr. Mohammad Abdus Salam';
UPDATE public.legacy_doctors SET designation = 'Medicine Specialist & Cardiologist  Clinical & Interventional Cardiologist  Professor & Head of the Department, Cardiology (Ret)' WHERE name = 'Professor. (Dr.) Md. Abdul Kader Akanda';
UPDATE public.legacy_doctors SET designation = 'Stroke Neurologist  Professor, Dept. of Neuromedicine' WHERE name = 'Professor (Dr.) Md. Shahidullah (Sabuj)';
UPDATE public.legacy_doctors SET designation = 'Consultant Cardiologist & Medicine Specialist' WHERE name = 'Dr. Md. Asifudduza (Asif)';
UPDATE public.legacy_doctors SET designation = 'Urology Specialist' WHERE name = 'Professor Dr. A Z M Zahid Hossain';
UPDATE public.legacy_doctors SET designation = 'Gastroenterology, Liver & Medicine Specialist Professor Dept. of Gastroenterology' WHERE name = 'Dr. Chanchal Kumar Ghosh';
UPDATE public.legacy_doctors SET designation = 'Member- Indian & British Society of Gastroenterology Member- American Gastroenterological Association Specialist in Medicine, Gastro-intestinal & Liver Diseases Ex. Professor & Head, Dept. of Gastroenterology' WHERE name = 'Professor Dr. Swapan Chandra Dhar';
UPDATE public.legacy_doctors SET designation = 'Associate Professor (Cardiology)' WHERE name = 'Dr. S. Mokaddas Hossain (Sadi)';
UPDATE public.legacy_doctors SET designation = 'Medicine Specialist, Senior Consultant, Medicine Dept.' WHERE name = 'Professor. Dr. Md. Monzur Rahman (Galib)';
UPDATE public.legacy_doctors SET designation = 'Gynecologist, Obstetrician & Laparoscopic Surgeon, Former Professor' WHERE name = 'Professor Dr. Afzalunnessa Chowdhury';
UPDATE public.legacy_doctors SET designation = 'Diabetes, Thyroid, Hormone & Medicine Specialist , Associate Professor (Diabetes & Endocrinology),Dhaka Medical College & Hospital' WHERE name = 'Dr. M Saifuddin';
UPDATE public.legacy_doctors SET designation = 'Professor of Neurology Neurologist & Medicine Specialist, Ex- Head of Clinical neurology' WHERE name = 'Professor. Dr. Md. Azharul Hoque';
UPDATE public.legacy_doctors SET designation = 'Stroke & Interventional Neurologist  Professor & Divisional Head' WHERE name = 'Professor Dr. Subash Kanti Dey';
UPDATE public.legacy_doctors SET designation = 'Ear Nose Throat & Head-Neck Surgeon  Ex. Consultant, Dhaka Medical College & Hospital & Cancer Hospital Ex. Associate Prof., Dept. of ENT & Head- Neck Surgery' WHERE name = 'Dr. M. R. Islam';
UPDATE public.legacy_doctors SET designation = 'Professor & Head, Dept. of Gastroenterology (Ex)' WHERE name = 'Professor Dr. Md. Ashraful Islam';
UPDATE public.legacy_doctors SET designation = 'Consultant Physician and Hepatologist FORMER Chairman, Department of Hepatology' WHERE name = 'Professor (Retd.) Dr. Nooruddin Ahmad';
UPDATE public.legacy_doctors SET designation = 'Laparoscopic Surgeon Obstetrician and Gynecologist  Ex. Executive Director & Head of the Dept., Obs. & Gynae' WHERE name = 'Professor Dr. Begum Hosne Ara';
UPDATE public.legacy_doctors SET designation = 'Cardiology, Chest Diseases & Medicine Specialist Professor' WHERE name = 'Professor Dr. S M Mustafa Zaman';
UPDATE public.legacy_doctors SET designation = 'Cardiology, Diabetes & Medicine Specialist Ex. Professor' WHERE name = 'Professor. (Dr.) M M Zahurul Alam Khan';
UPDATE public.legacy_doctors SET designation = 'Medicine, Diabetes, Thyroid & Hormone Disease Specialist (Endocrinologist),  Professor & Head, Dept. of Diabetes & Endocrinology Dhaka Medical College & Hospital' WHERE name = 'Professor Dr. Indrajit Prasad';
UPDATE public.legacy_doctors SET designation = 'Neuro & Spinal Surgeon  Professor, Department of Neurosurgery' WHERE name = 'Professor. Dr. Haradhan Deb Nath';
UPDATE public.legacy_doctors SET designation = 'Head of Medicine Dept. & Principal (Rtd.) Mymensingh Medical College Senior Consultant, Labaid Specialized Hospital' WHERE name = 'Professor. DR. SANKAR NARAYAN DAS';
UPDATE public.legacy_doctors SET designation = 'Bone & Joint Specialist & Spine Surgeon Ex. Consultant,  Sr. Consultant' WHERE name = 'Dr. Md. Zia Uddin';
UPDATE public.legacy_doctors SET designation = 'Urology Specialist  Professor, Urology & Kidney Transplant Surgery' WHERE name = 'Professor Dr. Tohid Md. Saiful Hossain (Dipu)';
UPDATE public.legacy_doctors SET designation = 'Consultant Urological Surgeon Ex. Consultant Surgeon General & Chief Urologist' WHERE name = 'Maj Gen Professor Dr. H R Harun';
UPDATE public.legacy_doctors SET designation = 'Professor, Department of Medicine   Medicine & Rheumatology Specialist' WHERE name = 'Prof. Dr. Shah Habibur Rahman';
UPDATE public.legacy_doctors SET designation = 'Newborn, Adolescent & Child Specialist (0 - 18 Years)  Professor, Chairman & Dean (Rtd.)' WHERE name = 'Professor Dr. Md. Habibur Rahman';
UPDATE public.legacy_doctors SET designation = 'Laparoscopic Surgeon, Gynae & Obs Specialist, Senior Consultant' WHERE name = 'Dr. Tasnim Akter';
UPDATE public.legacy_doctors SET designation = 'Internal Medicine Specialist & Neurologist  Chairman (Head of dept.) & Professor (Ex.),' WHERE name = 'Professor (dr.) M. A. Hannan';
UPDATE public.legacy_doctors SET designation = 'Brain and Spine Surgeon Associate professor, Neuro Surgery Dept.' WHERE name = 'Dr. Md. Rezaul Amin (Titu)';
UPDATE public.legacy_doctors SET designation = 'Kidney Specialist Professor' WHERE name = 'Professor. Dr. Asia Khanam';
UPDATE public.legacy_doctors SET designation = 'Professor, Skin & STD''S' WHERE name = 'Professor Dr. Mir Nazrul Islam';
UPDATE public.legacy_doctors SET designation = 'Breast, Laparoscopic & Colorectal Surgeon ,Associate Professor' WHERE name = 'Dr. Most. Bilkis Fatema';
UPDATE public.legacy_doctors SET designation = 'Ear, Nose, Throat, Head-Neck Specialist & Surgeon Professor & Heat of the Dept' WHERE name = 'Professor Dr. SK Nurul Fattah Rumi';
UPDATE public.legacy_doctors SET designation = 'Professor (Respiratory Medicine),   (Ex.) National Institute of Diseases of the Chest & Hospital (NIDCH)  Senior Consultant (Pulmonology & Sleep Medicine)' WHERE name = 'Professor. Dr. Zakir Hossain Sarkar';
UPDATE public.legacy_doctors SET designation = 'Professor, Respiratory Medicine Department Bangladesh Medical University (BMU)  Medicine, Pulmonologist & Sleep Medicine Specialist Labaid Specialized Hospital' WHERE name = 'Professor Dr. AKM Mosharraf Hossain';
UPDATE public.legacy_doctors SET designation = 'Gynae, Obs. Specialist & Surgeon, Associate Professor' WHERE name = 'Dr. Umme Salma Chowdhury (Shanta)';
UPDATE public.legacy_doctors SET designation = 'Clinical & Interventional Cardiologist & Medicine Specialist, Associate Professor (Cardiology)' WHERE name = 'Dr. A.K.S Zahid Mahmud Khan';
UPDATE public.legacy_doctors SET designation = 'Medicine & Rheumatology Specialist Associate Professor' WHERE name = 'Prof. Dr. Abu Shahin';
UPDATE public.legacy_doctors SET designation = 'Dermatologist, Laser & Hair Transplant Surgeon' WHERE name = 'Dr. Md. Quamrul Hassan Chowdhury';
UPDATE public.legacy_doctors SET designation = 'Specialist Internal Medicine & Diabetologist  Professor of Medicine' WHERE name = 'Professor Dr. Khwaja Nazim Uddin';
UPDATE public.legacy_doctors SET designation = 'Specialist in VD, Skin, Sex, Allergy & Leprosy Professor' WHERE name = 'Professor Lt. Col. (Retd.) Dr. Md. Abdul Wahab';
UPDATE public.legacy_doctors SET designation = 'Pulmonologist, Medicine & Allergy Specialist Chairman, Respiratory Medicine Dept.' WHERE name = 'Professor (Dr.) Mohammed Atiqur Rahman';
UPDATE public.legacy_doctors SET designation = 'Haematologist & BMT Physician Head of Haematology & BMT Unit' WHERE name = 'Professor Dr. M A Khan';
UPDATE public.legacy_doctors SET designation = 'Diabetes, Thyroid, Hormone & Medicine Specialist,  Assistant Professor' WHERE name = 'Dr. Marufa Mustari';
UPDATE public.legacy_doctors SET designation = 'Professor of Cardiology' WHERE name = 'Prof. (Dr.) M G Azam';
UPDATE public.legacy_doctors SET designation = 'Professor & Head of the Department Trauma, Orthopedic & Spine Surgeon Dept. Of Orthopedic & Spine Surgeon' WHERE name = 'Professor. Erfanul Huq Siddiqui';
UPDATE public.legacy_doctors SET designation = 'Former Director Cum Professor' WHERE name = 'Professor Dr. Moarraf Hossen';
UPDATE public.legacy_doctors SET designation = 'Dermatology, Venereology & Skin Laser Specialist Consultant' WHERE name = 'Dr. Isabela Kabir';
UPDATE public.legacy_doctors SET designation = 'Chest & Oesophageal Surgeon' WHERE name = 'Prof. Dr. Mosharraf Hossain (Shamim)';
UPDATE public.legacy_doctors SET designation = 'Pain Medicine & Rheumatology   Arthritis & Joint Disease Specialist' WHERE name = 'Professor Dr. Syed Mozaffar Ahmed';
UPDATE public.legacy_doctors SET designation = 'Professor of Pediatrics,  Ex. Academic Director' WHERE name = 'Professor Dr. Syed Khairul Amin';
UPDATE public.legacy_doctors SET designation = 'Professor of Psychotherapy, Senior -Chief Consultant (Psychiatry & Psychotherapy)' WHERE name = 'Prof.Dr. M A Mohit Kamal';
UPDATE public.legacy_doctors SET designation = 'Blood & Medicine Specialist Professor & Head, Dept. of Hematology' WHERE name = 'Professor Dr. Md. Sirajul Islam';
UPDATE public.legacy_doctors SET designation = 'Ex. Professor, Internal Medicine' WHERE name = 'Professor. Dr. Md. Abdul Jalil Chowdhury';
UPDATE public.legacy_doctors SET designation = 'Specialist Dermatology & Venereology Consultant' WHERE name = 'Dr. Mahmud Chowdhury';
UPDATE public.legacy_doctors SET designation = 'Pain Medicine & Rheumatology Specialist Professor' WHERE name = 'Professor Dr. A K M Salek';
UPDATE public.legacy_doctors SET designation = 'Professor & Head of the Dept.' WHERE name = 'Professor. Dr. Feroz Amin';
UPDATE public.legacy_doctors SET designation = 'Obstetrician & Gynecologist  Associate Professor' WHERE name = 'Dr. Kaniz Fatema';
UPDATE public.legacy_doctors SET designation = 'Pediatric Specialist Consultant, Dept. of Pediatrics & NICU' WHERE name = 'Dr. Ajmery Sultana Chowdhury';
UPDATE public.legacy_doctors SET designation = 'Ear-Nose-Throat Specialist & Head-Neck Surgeon Associate Professor (ENT) & Deputy Director' WHERE name = 'Dr. K. M. Mamun Murshed';
UPDATE public.legacy_doctors SET designation = 'Specialist in Neuromedicine & Medicine Professor of Neurology' WHERE name = 'Professor Dr. Mansur Habib';
UPDATE public.legacy_doctors SET designation = 'Urologist, Andrologist & Uro-oncologist Consultant, Urology & Uro-oncology' WHERE name = 'Prof. Dr. Md. Shaukat Ali Khan';
UPDATE public.legacy_doctors SET designation = 'Pediatric Neurologist Associate Professor' WHERE name = 'Associate Prof. Dr. Naznin Akter (Ruby)';
UPDATE public.legacy_doctors SET designation = 'Chief Consultant    Laser & Vitreo - Retinal Service' WHERE name = 'Dr. Ansarul Huq';
UPDATE public.legacy_doctors SET designation = 'Ex-Director' WHERE name = 'Professor (Dr.) Md.  Faruq Alam';
UPDATE public.legacy_doctors SET designation = 'Assistant Professor (Reproductive Endocrinology and Infertility Dept.) DNCC Dedicated Covid-19 Hospital' WHERE name = 'DR. SERAJOOM MUNIRA';
UPDATE public.legacy_doctors SET designation = 'E.N.T Specialist & Head-Neck Surgeon Ex. Professor & Head (E.N.T)' WHERE name = 'Professor Dr. Sabah Uddin Ahmed';
UPDATE public.legacy_doctors SET designation = 'Liver & Gastrointestinal Specialist Professor & Head, Dept. of Hepatology' WHERE name = 'Professor (Dr.) Faroque Ahmed';
UPDATE public.legacy_doctors SET designation = 'Professor of Plastic Surgery  Plastic Breast, Cosmetic Birth Defects, Skin, Tumors & Burn Surgeon' WHERE name = 'Dr. Foara Tasmim';
UPDATE public.legacy_doctors SET designation = 'Consultant Surgeon Professor & Head of the dept. Obs. & Gynae Department' WHERE name = 'Professor Dr. Shikha Ganguly';
UPDATE public.legacy_doctors SET designation = 'Psychiatrist, Counseling Expert & Psychotherapist  Professor, Psychiatry' WHERE name = 'Professor Dr. Saifun Nahar';
UPDATE public.legacy_doctors SET designation = 'Associate Professor, Dept. of Oncology  Bangladesh Medical University (Ex-PG Hospital)' WHERE name = 'Associate Professor. Dr. Shamsun Nahar';
UPDATE public.legacy_doctors SET designation = 'Hematology, Medicine and Blood Cancer Specialist' WHERE name = 'Dr. Md Ashikuzzaman';
UPDATE public.legacy_doctors SET designation = 'Cataract & Eye Specialist,Director & Professor (Ex)' WHERE name = 'Professor. (Dr.) G. M. Mostafa';
UPDATE public.legacy_doctors SET designation = 'Assistant Professor, Dept. of Anaesthesia Analgesia & Intensive Care Medicine' WHERE name = 'Dr. Chandra Shekhar Karmakar';
UPDATE public.legacy_doctors SET designation = 'Gynae, Obs Specialist & Surgeon' WHERE name = 'Dr. Tayeba Sultana';
UPDATE public.legacy_doctors SET designation = 'Professor & Head of the Dept. (Ex), Thoracic Surgery Dept.' WHERE name = 'Prof. Dr. Md. Shamsul Alam';
UPDATE public.legacy_doctors SET designation = 'Internal Medicine Specialist' WHERE name = 'Dr. Abed Hussain Khan';
UPDATE public.legacy_doctors SET designation = 'Assistant Professor, Vascular Surgery' WHERE name = 'Dr. Md. Bazlul Ghani Bhuiyan';
UPDATE public.legacy_doctors SET designation = 'Burn & Plastic Surgery Specialist   Professor (Plastic Surgery)' WHERE name = 'Dr. Maruf Alam Chowdhury';
UPDATE public.legacy_doctors SET designation = 'Senior Consultant' WHERE name = 'Dr. Khondaker Md. Masud';
UPDATE public.legacy_doctors SET designation = 'Senior Consultant' WHERE name = 'Dr. Md. Nurul Islam';
UPDATE public.legacy_doctors SET designation = 'BDS (Dhaka)' WHERE name = 'Dr. Nargis Salahuddin';
UPDATE public.legacy_doctors SET designation = 'M.Phil (Psychology), Ph.D (Psychology)' WHERE name = 'Dr. Chaya Bhattacharjee';
UPDATE public.legacy_doctors SET designation = 'Associate Professor  Physical Medicine & Rehabilitation Department' WHERE name = 'Dr. Md. Tariqul Islam';
UPDATE public.legacy_doctors SET designation = 'Kidney & Medicine Specialist Consultant' WHERE name = 'Dr. Sumon Chandra Roy';
UPDATE public.legacy_doctors SET designation = 'Nuclear Medicine & Thyroid' WHERE name = 'Prof. Dr. Md. Sayedur Rahman Miah';
UPDATE public.legacy_doctors SET designation = 'Specialist in Nuclear Medicine, Thyroid Specialist   Sr. Consultant, Labaid Ltd. (Diagnostic)' WHERE name = 'Professor. DR. MD. SANOWAR HOSSAIN';
UPDATE public.legacy_doctors SET designation = 'Associate Professor of Cardiology' WHERE name = 'Dr. Nur Alam';
UPDATE public.legacy_doctors SET designation = 'Assistant Professor (High Risk Pregnancy) Feto Maternal Medicine Department' WHERE name = 'Dr. Sharmin Ferdous (Koly)';
UPDATE public.legacy_doctors SET designation = 'Professor & Head (Ex.), Department of Endocrinology' WHERE name = 'Prof. Dr. Md. Ruhul Amin';
UPDATE public.legacy_doctors SET designation = 'Medicine, Diabetes, Rheumatology & Chest Diseases Specialist, Professor, Dept. of Medicine, Ibrahim Medical College, Ex-Professor & Head of the Dept. of Medicine BIRDEM & Ibrahim Medical College' WHERE name = 'Prof. (Dr.) A.K.M. Musa';
UPDATE public.legacy_doctors SET designation = 'General & Laparoscopic Surgeon Assistant Professor' WHERE name = 'DR. A. Z. MAHMUDUL HASAN KANAK';
UPDATE public.legacy_doctors SET designation = 'Vascular & Endovascular Surgeon National Institute of Cardiovascular Disease' WHERE name = 'Dr. HM Ashfaq Nazmi';
UPDATE public.legacy_doctors SET designation = 'Vascular & Endovascular Surgeon National Institute of Cardiovascular Disease' WHERE name = 'Dr. Nagib Mahfuz Khan';
UPDATE public.legacy_doctors SET designation = 'Urology Specialist & Surgeon, Assistant Professor (Urology), National Institute of Kidney Diseases & Urology (NIKDU), Sher-Bangla Nagor, Dhaka' WHERE name = 'Dr. Md. Nasir Uddin';
UPDATE public.legacy_doctors SET designation = 'Orthopedic & Joint replacement Surgeon. Head of Arthroscopy and Arthroplasty Division. Bangladesh Medical University (Ex-PG Hospital)' WHERE name = 'Professor Dr. Sheikh Forhad';
UPDATE public.legacy_doctors SET designation = 'Advanced Laparoscopic Colorectal Gastrointestinal (Including Hepatobiliary) & General Surgeon Professor & Head, Dept. of Surgical Gastroenterology, National Gastroliver Institute & Hospital, Dhaka' WHERE name = 'Prof. Dr. Md. Mamunur Rahman';
UPDATE public.legacy_doctors SET designation = 'Ear, Nose, Throat & Head-Neck Surgeon Assistant Professor & Head of the Department ,Dhaka Central International Medical College Hospital' WHERE name = 'Dr. Md. Shafiqul Islam';
UPDATE public.legacy_doctors SET designation = 'Assistant Professor, Neurology Department' WHERE name = 'Dr. Shahida Bulbul';
UPDATE public.legacy_doctors SET designation = 'Associate Professor, Department of Paediatric Nephrology' WHERE name = 'Dr. Syed Saimul Huque';
UPDATE public.legacy_doctors SET designation = 'Clinical & Interventional Cardiologist, Head of the Department, Medicine Department, AFMC' WHERE name = 'Prof. Brig. General Dr. Md. Wali-Ur-Rahman';
UPDATE public.legacy_doctors SET designation = 'Head, Pediatric Surgery Department' WHERE name = 'Prof. Dr. Mirza Kamrul Zahid';
UPDATE public.legacy_doctors SET designation = 'Medicine, Gastroenterology & Liver Specialist  Consultant, Department of Medicine' WHERE name = 'Dr. Md. Kamrul Hasan';
UPDATE public.legacy_doctors SET designation = 'Liver, Gastroenterology & Medicine Specialist  Senior Consultant' WHERE name = 'Dr. Kazi Monisur Rahman';
UPDATE public.legacy_doctors SET designation = 'Professor & Head (Rtd.), Department of Neurosurgery' WHERE name = 'Prof. Dr. M. M. Ehsanul Haque';
UPDATE public.legacy_doctors SET designation = 'Associate Professor, Pediatric Orthopedics surgery' WHERE name = 'Dr. Quazi Shahid-Ul-Alam';
UPDATE public.legacy_doctors SET designation = 'Professor , Medicine Specialist.' WHERE name = 'Prof. Dr. Rubina Yasmin';
UPDATE public.legacy_doctors SET designation = 'Brain, Spine, Spinal Cord Microsurgery & Endoscopic Surgery Specialist ,Senior Consultant, Labaid Specialized Hospital' WHERE name = 'Prof. Dr. B Karim';
UPDATE public.legacy_doctors SET designation = 'Surgical Oncologist & Oncoplastic Breast Surgeon, General,Laparoscopic & Colorectal Surgeon, Professor, Surgery and Surgical Oncology, CMH, Dhaka' WHERE name = 'Professor Colonel (Dr) Nasir Uddin (Mahmud) BGBMS';
UPDATE public.legacy_doctors SET designation = 'Professor of Cardiology' WHERE name = 'Prof. (Dr.) Razia Sultana Mahmud';
UPDATE public.legacy_doctors SET designation = 'Professor (Gastro)  Medicine, Liver & Gastrointestinal Disease Specialist' WHERE name = 'Prof. Dr. Swapan Kumar Sarkar';
UPDATE public.legacy_doctors SET designation = 'Associate Professor (Cardiology)' WHERE name = 'DR. LOHANI MD. TAJUL ISLAM';
UPDATE public.legacy_doctors SET designation = 'Sr. Consultant Cardiac Surgery Dept.' WHERE name = 'DR. AMIRUL ISLAM BHUYAN';
UPDATE public.legacy_doctors SET designation = 'Associate Professor (Cardiology) National Institute of Cardiovascular Diseases & Hospital' WHERE name = 'Dr. Mustafizur Rahman';
UPDATE public.legacy_doctors SET designation = 'General, Laparoscopic, Hepatobiliary & Pancreatic Surgeon Associate Professor & Head  Dept. of Hepatobiliary & Pancreatic Surgery' WHERE name = 'Dr. Akhter Ahmed (Shuvo)';
UPDATE public.legacy_doctors SET designation = 'Assistant Professor, Department of Nephrology National Institute of Kidney Diseases & Urology, Dhaka' WHERE name = 'Dr. Abu Zafor Md. Salahuddin';
UPDATE public.legacy_doctors SET designation = 'Consultant' WHERE name = 'Dr. Mohammad Sohel-Uzzaman';
UPDATE public.legacy_doctors SET designation = 'Consultant' WHERE name = 'Dr. AKM Mustakim Billah';
UPDATE public.legacy_doctors SET designation = 'Consultant' WHERE name = 'Dr. Md. Khalid Bin Rahman Apourba';
UPDATE public.legacy_doctors SET designation = 'Consultant' WHERE name = 'Dr. Asif Yazdani';
UPDATE public.legacy_doctors SET designation = 'Consultant' WHERE name = 'Dr. Shafiqul Islam';
UPDATE public.legacy_doctors SET designation = 'Consultant' WHERE name = 'Dr. Mostak Ahmed';
UPDATE public.legacy_doctors SET designation = 'Kidney Diseases Specialist  Associate Professor & Unit Head Department of Nephrology National Institute of Kidney' WHERE name = 'Dr. Shah Newaz Dewan';
UPDATE public.legacy_doctors SET designation = 'Consultant, Dept. of Cardiac Surgery' WHERE name = 'Dr. Akhter Hamid Parvez';
UPDATE public.legacy_doctors SET designation = 'Senior Consultant & Deputy Director, Cardiac Cath Lab' WHERE name = 'Dr. Mohammad Abul Khayer';
UPDATE public.legacy_doctors SET designation = 'Consultant Cardiology' WHERE name = 'Dr. Rashiduz Zaman';
UPDATE public.legacy_doctors SET designation = 'Consultant, Cardiology' WHERE name = 'Dr. Mohammad Ziaul Kabir';
UPDATE public.legacy_doctors SET designation = 'Consultant, Clinical & Interventional Cardiologist' WHERE name = 'Dr. Shiblee Sadik Pathan';
UPDATE public.legacy_doctors SET designation = 'Consultant Cardiologist' WHERE name = 'Dr. Md Jaglul Kabir';
UPDATE public.legacy_doctors SET designation = 'Gynecology, Obstetrics & Infertility Specialist & Surgeon Assistant Professor (Gynae & Obs)' WHERE name = 'Dr. Tahmina Akter';
UPDATE public.legacy_doctors SET designation = 'General, Laparoscopic & Colorectal Surgeon Casualty, Accident & Trauma Surgeon Associate Professor (Casualty Surgery)' WHERE name = 'Dr. Md. Arif Hossain';
UPDATE public.legacy_doctors SET designation = 'Consultant Cardiologist & Medicine Specialist' WHERE name = 'Dr. Md. Mohasin Uddin';
UPDATE public.legacy_doctors SET designation = 'Interventional Cardiologist & Electrophysiologist, Professor of Cardiology' WHERE name = 'Professor. Dr. Md. Mohsin Hossain';
UPDATE public.legacy_doctors SET designation = 'Senior Consultant' WHERE name = 'Prof Dr. Amzad Hossain';
UPDATE public.legacy_doctors SET designation = 'Maxillofacial Surgeon' WHERE name = 'Prof. Dr. Nasir Uddin';
UPDATE public.legacy_doctors SET designation = 'Consultant' WHERE name = 'Prof. Dr. Zakir Ahmed Shaheen';
UPDATE public.legacy_doctors SET designation = 'Consultant' WHERE name = 'Dr. Safiqur Rahman Khan';
UPDATE public.legacy_doctors SET designation = 'Consultant' WHERE name = 'Dr. Mohammad Shamim al Mamun';
UPDATE public.legacy_doctors SET designation = 'Infertility Specialist & Laparoscopic Surgeon' WHERE name = 'Dr. Juthi Bhowmik';
UPDATE public.legacy_doctors SET designation = 'Oral & Dental Surgeon' WHERE name = 'Dr. Nirmal Sharma';
UPDATE public.legacy_doctors SET designation = 'Liver, Gallbladder, Bile Duct & Pancreatic Surgeon' WHERE name = 'Dr. Sarwar Ahmed Sobhan';
UPDATE public.legacy_doctors SET designation = 'Consultant' WHERE name = 'Dr. Fariha Binte Quayum';
UPDATE public.legacy_doctors SET designation = 'Pediatric Gastroenterology, Hepatology  Nutrition & Child Specialist, Associate Professor.' WHERE name = 'Dr. Md. Shariful Hasan';
UPDATE public.legacy_doctors SET designation = 'Ear, Nose, Throat, Thyroid, Sinusitis &  Sleep Disorder Specialist & Surgeon  Associate Professor, Department of ENT' WHERE name = 'Dr. Md. Mazibur Rahman Meaji';
UPDATE public.legacy_doctors SET designation = 'Consultant' WHERE name = 'Dr. Kazi Rumana Sharmin Rummee';
UPDATE public.legacy_doctors SET designation = 'Senior Oral & Dental Surgeon' WHERE name = 'Dr. Md. Sanowar Hossain Khan';
UPDATE public.legacy_doctors SET designation = 'Neurology Specialist, Associate Professor, Department of Neurology' WHERE name = 'Dr. Kazi Jannat Ara';
UPDATE public.legacy_doctors SET designation = 'Advanced Colorectal & Laparoscopic Surgeon, Associate Professor' WHERE name = 'Dr. Muhammad Ali Siddiquee';
UPDATE public.legacy_doctors SET designation = 'General & Laparoscopic Surgeon Ex. Professor of Department Surgery,BMU (PG Hospital), Dhaka' WHERE name = 'Prof. Dr. A.K.M Ahsan Ullah';
